name: Trigger Netlify Birthday Function # Changed name slightly for clarity

on:
  schedule:
    # Runs "at 08:00 UTC every day" (using your existing schedule)
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  trigger_netlify_function: # Changed job name for clarity
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Function
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          "https://txblogin.netlify.app/api/cron/trigger-birthdays"